{
  "motor_noise": # 70 dB
    {
    "amplitude":  3162.28,    # main signal
    "frequency": 80.6,     # Hz
    "phase": 0
    },
  "white_noise": # Is actually ambiant noise 40 dB
    {
    "amplitude":  100,    # main signal
    "frequency": 100,     # Hz
    "phase": 0
    },
  "explosion_noise": # 140dB
    {
    "amplitude":  10000000,  # main signal A=10^(L/20)
    "frequency": 35,     # Hz
    "phase": 0
    }
}