[
  {"lat": 43.13471,   # deg
  "lon": 6.01507,     # deg
  "alt": 6.0,         # Height above mean sea (m)
  "start_time": 15,   # (s)
  "lenght": 10},      # (s)

  {"lat": 43.13471,   # deg CHANGE
  "lon": 6.015195909,     # deg CHANGE
  "alt": 6.0,         # Height above mean sea (m)
  "start_time": 25,   # (s)
  "lenght": 10},      # (s)
]