[
  # SOURCE 1 Mobile
  {"lat": 43.13470855,   # deg CHANGE
  "lon": 6.01543980,     # deg CHANGE
  "alt": 6.0,         # Height above mean sea (m)
  "start_time": 10,   # (s)
  "lenght": 10},      # (s)

  {"lat": 43.13475282,   # deg CHANGE
  "lon": 6.01550104,     # deg CHANGE
  "alt": 6.0,         # Height above mean sea (m)
  "start_time": 15,   # (s)
  "lenght": 10},      # (s)

  {"lat": 43.13470904,   # deg CHANGE
  "lon": 6.01556233,     # deg CHANGE
  "alt": 6.0,         # Height above mean sea (m)
  "start_time": 20,   # (s)
  "lenght": 10},      # (s)

  # SOURCE 2 Mobile
  {"lat": 43.13488820,   # deg CHANGE
  "lon": 6.01457683,     # deg CHANGE
  "alt": 6.0,         # Height above mean sea (m)
  "start_time": 10,   # (s)
  "lenght": 10},      # (s)

  {"lat": 43.13492082,   # deg CHANGE
  "lon": 6.01450361,     # deg CHANGE
  "alt": 6.0,         # Height above mean sea (m)
  "start_time": 15,   # (s)
  "lenght": 10},      # (s)

  {"lat": 43.13497343,   # deg CHANGE
  "lon": 6.01445386,     # deg CHANGE
  "alt": 6.0,         # Height above mean sea (m)
  "start_time": 20,   # (s)
  "lenght": 10},      # (s)

  # SOURCE 3 Static
  {"lat": 43.13461847,   # deg CHANGE
  "lon": 6.01506918,     # deg CHANGE
  "alt": 6.0,         # Height above mean sea (m)
  "start_time": 10,   # (s)
  "lenght": 10},      # (s)

  {"lat": 43.13461847,   # deg CHANGE
  "lon": 6.01506918,     # deg CHANGE
  "alt": 6.0,         # Height above mean sea (m)
  "start_time": 15,   # (s)
  "lenght": 10},      # (s)

  {"lat": 43.13461847,   # deg CHANGE
  "lon": 6.01506918,     # deg CHANGE
  "alt": 6.0,         # Height above mean sea (m)
  "start_time": 20,   # (s)
  "lenght": 10},      # (s)
]